
liip_imagine:
    filter_sets:
        thumb:
            quality: 100
            filters:
                thumbnail:
                    size: [360,320]
                    mode: outbound
        medium:
            quality: 100
            filters:
                thumbnail:
                    size: [700,530]
                    mode: outbound

        profile:
            quality: 100
            filters:
                thumbnail:
                    size: [400,300]
                    mode: outbound

        large:
            quality: 100
            filters:
                thumbnail:
                    size: [1200,500]
                    mode: outbound

# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
#liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    #driver: "gd"
