vich_uploader:
    db_driver: orm

    mappings:
        annonce_image:
            uri_prefix: /images/annonces
            upload_destination: '%kernel.project_dir%/public/images/annonces'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        doyen_image:
            uri_prefix: /images/doyen
            upload_destination: '%kernel.project_dir%/public/images/doyen'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        alumni_image:
            uri_prefix: /images/alumnis
            upload_destination: '%kernel.project_dir%/public/images/alumnis'
            namer: Vich\UploaderBundle\Naming\UniqidNamer

        uploads:
            uri_prefix: /uploads
            upload_destination: '%kernel.project_dir%/public/uploads'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
